name: Publish packages to PyPI

on:
  create:
    tags: "*"

jobs:
  publish:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: MatteoH2O1999/setup-python@v4
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        pip install "setuptools >= 40.9"
        pip install .
    - name: Create packages
      run: python setup.py sdist bdist_wheel
    - name: Upload packages
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.pypi_password }}
